/*
 * @(#)mccsimulink.h    generated by: makeheader    Mon Oct 16 01:58:49 2000
 *
 *		built from:	mlm/mex_simulink.c
 */

#ifndef mccsimulink_h
#define mccsimulink_h

#ifdef __cplusplus
    extern "C" {
#endif


#if defined(MATLAB_MEX_FILE)


/*
 * Copyright (c) 1984-1999 The MathWorks, Inc.
 * All Rights Reserved.
 */
#include "simstruc.h"


extern void mclInitializeSizes(SimStruct * S, int_T u, int_T y);


extern void mclInitializeSampleTimes(SimStruct * S);


extern void mclOutputs(real_T * y, real_T const * x, real_T const * u,
                SimStruct * S, int_T tid, mxFunctionPtr F);


extern void mclSimulink( real_T * y,
                  real_T const * x,
                  real_T const * u,
                  SimStruct * S,
                  int_T tid, 
                  mxFunctionPtr mlxF, 
                  mex_information info );


#endif

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* mccsimulink_h */
